# Generated by Django 2.2.1 on 2019-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(default='2018', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
